import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/providers/theme-provider"
import "./globals.css";
import { ThemeToggle } from "@/components/theme-toggle";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className="fixed right-4 top-4">
              <ThemeToggle />
            </div>
            <div className="flex">
              <Header />
              <div className="content-body">
                {children}
              </div>
            </div>  
          </ThemeProvider>
        </body>
    </html>
  );
}
